config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'


  get "admin", controller: :admin, action: :index, as: :admin_root
  devise_for :usuarios, path: 'admin', path_names: { sign_in: 'entrar', sign_out: 'sair' }, controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :postagens
  end

  get "single_postagem/:id" => "site#single_postagem", as: :single_postagem

  get "up" => "rails/health#show", as: :rails_health_check



  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/postagens_controller.rb
class Admin::PostagensController < AdminController
  before_action :set_postagem, only: %i[ show edit update destroy ]

  # GET /postagens or /postagens.json
  def index
    @postagens = Postagem.all
  end

  # GET /postagens/1 or /postagens/1.json
  def show;end

  # GET /postagens/new
  def new
    @postagem = Postagem.new
  end

  # GET /postagens/1/edit
  def edit
  end

  # POST /postagens or /postagens.json
  def create
    @postagem = Postagem.new(postagem_params)

    respond_to do |format|
      if @postagem.save
        format.html { redirect_to admin_postagem_url(@postagem), notice: "Postagem Criada." }
        format.json { render :show, status: :created, location: @postagem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @postagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postagens/1 or /postagens/1.json
  def update
    respond_to do |format|
    if @postagem.update(postagem_params)
        format.html { redirect_to admin_postagem_url(@postagem), notice: "Postagem Atualizada" }
        format.json { render :show, status: :ok, location: @postagem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @postagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postagens/1 or /postagens/1.json
  def destroy
    @postagem.destroy!
    respond_to do |format|
      format.html { redirect_to admin_postagens_url, notice: "Postagem Deletada" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postagem
      @postagem = Postagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postagem_params
      params.require(:postagem).permit(:titulo, :data, :conteudo)
    end
end

app/helpers/postagens_helper.rb
module PostagensHelper
end

app/views/admin/postagens/_form.html.erb
<%= form_with(model: [:admin, postagem]) do |form| %>
  <% if postagem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(postagem.errors.count, "error") %> prohibited this postagem from being saved:</h2>

      <ul>
        <% postagem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.datetime_field :data %>
  </div>

  <div>
    <%= form.label :conteudo, style: "display: block" %>
    <%= form.rich_text_area :conteudo, class: "form-control", style: "width: 600px; height: 200px;" %>

  <div>
    <%= form.submit "Salvar Postagem" %>
  </div>
<% end %>

app/views/admin/postagens/_postagem.html.erb
<% resource ||= postagem %>
  
  <div id="<%= dom_id postagem %>">
  <p>
    <strong>Titulo:</strong>
    <%= resource.titulo %>
  </p>

  <p>
    <strong>Data:</strong>
  <%= resource.data.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Conteudo:</strong>
    <%= resource.try(:conteudo) %>
  </p>

</div>

app/views/admin/postagens/edit.html.erb
<h1>Editando Postagem</h1>

<%= render "form", postagem: @postagem %>

app/views/admin/postagens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Postagens</h1>
<p><em>Ultimas Postagens:</em></p>

<div id="postagens">
  <% @postagens.each do |postagem| %>
    <tr>
      <td> <strong><%= postagem.titulo %> </strong> </td>
      <td> <%= link_to "Visualizar", admin_postagem_path(postagem) %>
      <td> <%= link_to "Editar", edit_admin_postagem_path(postagem) %>
      <td> <%= button_to "Excluir", admin_postagem_path(postagem), method: :delete %> 
    </tr>
  <% end %>
</div>  

<%= link_to "Escrever Postagem", new_admin_postagem_path %>

app/views/admin/postagens/new.html.erb
<h1>Nova postagem</h1>

<%= render "form", postagem: @postagem %>

<br>

<div>
  <%= link_to "Voltar", admin_postagens_path %>
</div>

app/views/admin/postagens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @postagem %>

<tr>
  <td> <%= link_to "Editar", edit_admin_postagem_path %>
  <td> <%= button_to "Excluir", admin_postagem_path, method: :delete %> 
</tr>