config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'


  get "admin", controller: :admin, action: :index, as: :admin_root
  devise_for :usuarios, path: 'admin', path_names: { sign_in: 'entrar', sign_out: 'sair' }, controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :postagens
  end

  get "single_postagem/:id" => "site#single_postagem", as: :single_postagem

  get "up" => "rails/health#show", as: :rails_health_check



  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div>
        <%= link_to "Postagens",  admin_postagens_path %>
        <%= button_to "Encerrar Sessão", destroy_usuario_session_path, method: :delete %>
      </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luizdev Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <h1> Luizdev Blog </h1>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <body>
    <!-- login page -->
    <div id="login-page">
        <div class="container">
            <div class="row justify-content-center mt-5 pt-5">
                <div class="col-md-4">
                    <div class="card shadow p-4">
                        <div class="card-body">
                            <!-- api placeholder image -->
                            <div class="text-center mb-4">
                            </div>
                            <%= yield %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
  </body>
</html>